services:
  - type: web
    name: nasa-bioscience
    env: docker
    dockerfilePath: ./Dockerfile
    buildCommand: |
      docker build -t nasa-bioscience .
    startCommand: docker run -p 10000:10000 nasa-bioscience
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: "false"
      - key: VITE_APP_URL
        value: https://${RENDER_EXTERNAL_HOSTNAME}